#################################
#         Backend / VM          #
#################################
backend = "xrender";
vsync = false;
use-damage = true;
unredir-if-possible = true;

# Detección automática
detect-rounded-corners = true;
detect-client-opacity = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;

#################################
#            Bordes             #
#################################
corner-radius = 12;
rounded-corners-exclude = [
  #"class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

#################################
#            Sombras            #
#################################
shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "class_g ?= 'Dunst'",
  "_GTK_FRAME_EXTENTS@",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'tooltip'"
];

#################################
#           Opacidad            #
#################################
active-opacity = 1.0;
inactive-opacity = 0.92;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "95:class_g = 'FerreT'",
  "92:class_g = 'kitty' && focused",
  "85:class_g = 'kitty' && !focused",
  "100:class_g = 'firefox'",
  "100:class_g = 'Polybar'",
  "95:class_g = 'Rofi'"
];

#################################
#         Performance           #
#################################
fading = false;
