;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Global WM Settings

[global/wm]
margin-bottom = 0
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; File Inclusion

include-file = ~/.config/polybar/hack/bars.ini
include-file = ~/.config/polybar/hack/colors.ini
include-file = ~/.config/polybar/hack/modules.ini
include-file = ~/.config/polybar/hack/user_modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Bar Settings

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true

width = 100%
height = 26
offset-x = 0%
offset-y = 0%

background = ${color.background}
foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

underline-size = 2
underline-color = ${color.foreground}

padding = 1
module-margin-left = 0
module-margin-right = 0

font-0 = "Iosevka Nerd Font:pixelsize=10;3"
font-1 = "Iosevka Nerd Font:pixelsize=12;4"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/top]
inherit = bar/main
border-bottom-size = 2
border-bottom-color = ${color.primary}
modules-left = launcher sep title
modules-center = workspaces
; HE QUITADO: battery, checknet (para evitar errores en VM por ahora)
modules-right = target color-switch sep date sep sysmenu
enable-ipc = true

[bar/bottom]
inherit = bar/main
bottom = true
border-top-size = 2
border-top-color = ${color.primary}
; HE QUITADO: mpd (daba error connection refused)
modules-left = 
; HE QUITADO: temperature, speed (daban error en VM)
modules-center = cpu sep memory sep filesystem sep updates
; HE QUITADO: brightness (VM no tiene brillo)
modules-right = volume
enable-ipc = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

separator =
dim-value = 1.0
wm-name = 
locale = 

tray-position = none
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =

cursor-click = 
cursor-scroll = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = true

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
